# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the unit tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build screengrabDebug and test APK for screenshots"
  lane :build_and_screengrab do
    adb(command: "shell pm clear ltd.grunt.litewallet") rescue nil
    gradle(
        tasks: ['clean', 'assembleScreengrabDebug', 'assembleScreengrabAndroidTest']
    )
    screengrab(
        clear_previous_screenshots: true,
        app_apk_path: "app/build/outputs/apk/screengrab/debug/app-screengrab-debug.apk",
        tests_apk_path: "app/build/outputs/apk/androidTest/screengrab/debug/app-screengrab-debug-androidTest.apk"
    )
  end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
#
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
end
